apiVersion: batch/v1
kind: CronJob
metadata:
  name: uptime-checker
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: uptime-checker
            image: uptime-checker:latest
            imagePullPolicy: Never
          restartPolicy: OnFailure